name: green_example
description: Example app for green package
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  green:
    path: ../
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  gameframework:
    path: ../../../xraph/gameframework/packages/gameframework
  gameframework_unity:
    path: ../../../xraph/gameframework/engines/unity/dart

flutter:
  uses-material-design: true
